stages:
  - test

test:
  image: ubuntu:latest
  stage: test
  allow_failure: false
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y python-virtualenv python3-pip
    - python3 -m venv test_environment
    - . test_environment/bin/activate
    - make pip-install
    - make install-nvm
  script:
    - make lint
  # coverage: '/TOTAL.*\s+(\d+%)$/'

